/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : FDisp1.h
**     Project     : Lab2_NokiaDisplay
**     Processor   : MK64FN1M0VLL12
**     Component   : FontDisplay
**     Version     : Component 01.195, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-01-12, 20:49, # CodeGen: 6
**     Abstract    :
**
**     Settings    :
**          Bean name                                      : FDisp1
**          System                                         : 
**            InhGDisplay                                  : GDisp1
**     Contents    :
**         GetFontHeight   - void FDisp1_GetFontHeight(FDisp1_Font *font, FDisp1_PixelDim *charHeight,...
**         GetStringHeight - FDisp1_PixelDim FDisp1_GetStringHeight(byte *str, FDisp1_Font *font,...
**         GetCharWidth    - void FDisp1_GetCharWidth(byte ch, FDisp1_PixelDim *charWidth, FDisp1_PixelDim...
**         GetStringWidth  - FDisp1_PixelDim FDisp1_GetStringWidth(byte *str, FDisp1_Font *font,...
**         WriteString     - void FDisp1_WriteString(byte *str, FDisp1_PixelColor color, FDisp1_PixelDim...
**         WriteChar       - void FDisp1_WriteChar(byte ch, FDisp1_PixelColor color, FDisp1_PixelDim...
**
**     License   :  Open Source (LGPL)
**     Copyright : (c) Copyright Damian Schmid, Erich Styger, 2011, all rights reserved.
**     This an open source software in the form of a Processor Expert Embedded Component.
**     This is a free software and is opened for education,  research  and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file FDisp1.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup FDisp1_module FDisp1 module documentation
**  @{
*/         

#ifndef __FDisp1_H
#define __FDisp1_H

/* MODULE FDisp1. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "GDisp1.h"
#include "Cour8.h"

#include "Cpu.h"

typedef GDisp1_PixelDim   FDisp1_PixelDim; /* type which can hold a integral type for the x/y pixel dimension. This is depending on the display used. */
typedef GDisp1_PixelColor FDisp1_PixelColor; /* Type definining the color type (depens on display used). */
typedef GFONT_Callbacks FDisp1_Font;   /* Pointer to GFONT_Callbacks */




void FDisp1_WriteString(byte *str, FDisp1_PixelColor color, FDisp1_PixelDim *xCursor, FDisp1_PixelDim *yCursor, FDisp1_Font *font);
/*
** ===================================================================
**     Method      :  FDisp1_WriteString (component FontDisplay)
**     Description :
**         Function to write a string or character at the startpoint.
**         Set the startpoint with the function setCursor.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to the character string
**         color           - Foreground color to be used (for the
**                           character pixels)
**       * xCursor         - Pointer to x position of first
**                           character (upper left corner). On return
**                           this will contain the next y position.
**       * yCursor         - Pointer to y position of character
**                           (upper left corner). On return this will
**                           contain the next y position.
**       * font            - Pointer to font information
**     Returns     : Nothing
** ===================================================================
*/

void FDisp1_WriteChar(byte ch, FDisp1_PixelColor color, FDisp1_PixelDim *xCursor, FDisp1_PixelDim *yCursor, FDisp1_Font *font);
/*
** ===================================================================
**     Method      :  FDisp1_WriteChar (component FontDisplay)
**     Description :
**         Function to write a character at the start point. Set the
**         start point with the function setCursor.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - the character to print
**         color           - Foreground color to be used (for the
**                           character pixels)
**       * xCursor         - Pointer to x position of character
**                           (upper left corner). On return this will
**                           contain the next x position.
**       * yCursor         - Pointer to y position of character
**                           (upper left corner). On return this will
**                           contain the next y position.
**       * font            - Pointer to font information
**     Returns     : Nothing
** ===================================================================
*/

void FDisp1_GetCharWidth(byte ch, FDisp1_PixelDim *charWidth, FDisp1_PixelDim *totalWidth, FDisp1_Font *font);
/*
** ===================================================================
**     Method      :  FDisp1_GetCharWidth (component FontDisplay)
**     Description :
**         returns the width (in pixels) of a font character.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - character for which to calculate the width
**       * charWidth       - Pointer to width of the
**                           character in pixels (this is only for the
**                           character, without the space after the
**                           character)
**       * totalWidth      - Pointer to the total width
**                           of the character, including to the space
**                           after the character.
**       * font            - Pointer to font information
**     Returns     : Nothing
** ===================================================================
*/

FDisp1_PixelDim FDisp1_GetStringWidth(byte *str, FDisp1_Font *font, FDisp1_PixelDim *lastCharSpace);
/*
** ===================================================================
**     Method      :  FDisp1_GetStringWidth (component FontDisplay)
**     Description :
**         returns the width (in pixels) of a font string. For multiple
**         line strings (separated by \
**         ) or for strings with \r it returns the longest string
**         length.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to the string.
**       * font            - Pointer to font information
**       * lastCharSpace   - Pointer to the width
**                           of the last character space, useful if you
**                           combine multiple strings. The pointer may
**                           be NULL.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void FDisp1_GetFontHeight(FDisp1_Font *font, FDisp1_PixelDim *charHeight, FDisp1_PixelDim *totalHeight);
/*
** ===================================================================
**     Method      :  FDisp1_GetFontHeight (component FontDisplay)
**     Description :
**         returns the height (in pixels) of a font.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * font            - Pointer to font information
**       * charHeight      - Pointer to height of the
**                           character in pixels.
**       * totalHeight     - Pointer to the total
**                           height of the character, including to the
**                           space below the character.
**     Returns     : Nothing
** ===================================================================
*/

FDisp1_PixelDim FDisp1_GetStringHeight(byte *str, FDisp1_Font *font, FDisp1_PixelDim *lastLineSpace);
/*
** ===================================================================
**     Method      :  FDisp1_GetStringHeight (component FontDisplay)
**     Description :
**         returns the height (in pixels) of a font string. For
**         multiple line strings (separated by newline) or for strings
**         with \r it returns the longest list.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to the string.
**       * font            - Pointer to font information
**       * lastLineSpace   - Pointer to the height
**                           of the last line space, useful if you
**                           combine multiple strings. The pointer may
**                           be NULL.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

/* END FDisp1. */

#endif
/* ifndef __FDisp1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.11]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
